on: push
name: Clippy check
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["basic"]

    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ${{ matrix.dir }}/Cargo.toml
